# Generated by Django 6.0.3 on 2026-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('fuente', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_nombre', models.CharField(max_length=100)),
                ('empleado_cedula', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
