# Generated by Django 6.0.3 on 2026-04-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50, null=True)),
                ('documento', models.IntegerField(unique=True)),
                ('estado', models.BooleanField(default=False)),
                ('correo', models.EmailField(default='Error@validation.com', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=60)),
                ('abreviatura', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.CharField(max_length=80)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', related_query_name='nomina', to='RecursosHumanos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecursosHumanos.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecursosHumanos.cargo')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', related_query_name='contrato', to='RecursosHumanos.empleado')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecursosHumanos.tipocontrato')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.tipodocumento'),
        ),
    ]
