# Generated by Django 6.0.3 on 2026-03-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', related_query_name='contrato', to='RecursosHumanos.empleado'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', related_query_name='nomina', to='RecursosHumanos.empleado'),
        ),
    ]
